### ISSUE TITLE
How to use it？

### ISSUE THREAD

**Issue by seekcx** [dkamenka/nuxt-refresh-jwt#1]
I hope to have a simple instructions, I looked at the code, but I don't know how to use it.

**Comment by dkamenka** [comment]
It extends auth module for nuxt. It sends requests to refresh URL in 
specific interval and then replace token. In nuxt.config.js include this 
module after @nuxtjs/auth. Ex.:

   modules: [
     "@nuxtjs/axios",
     "@nuxtjs/auth",
     "nuxt-refresh-jwt"
   ],

You can overrides defaults in nuxt.config.js. Ex.:

   refreshJWT: {
     endpoint: { url: "/auth/refresh", method: "get" },
     interval: 10 * 60
   }

**Comment by seekcx** [comment]
I used it, found a problem:

 - After the refresh, the token becomes `undefined`.
 - Refresh response 401 is still retrying.

I don't know if there is a problem with my use or something else. I haven't figured out the principles of this component yet, and I can participate in it if needed.
